name = "netliy-review"
main = "./workers/app.js"
compatibility_date = "2026-07-09"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./dist/client"

[observability.logs]
enabled = true
